# Generated by Django 3.2.7 on 2021-09-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encryption_key', models.CharField(max_length=200)),
                ('encrypted_value', models.CharField(max_length=500)),
            ],
        ),
    ]
